### ISSUE TITLE
malformed format string - %S

### ISSUE THREAD

**Issue by ArttuTuo** [tbleicher/su2rad#27]
Hello 

For the past two months, I have not been able to use this extension due to the below error:
![image](https://user-images.githubusercontent.com/56154607/134328996-3fe78426-0982-4078-acfd-a75e5744c043.png)

"%S" does not even exist in the files on the mentioned lines but it's always "%s".
I've used this extension for more than a year now. I used it without problems at least on July 22.
Do you know how I should proceed to be able to get rid of this error?

Kind regards
Arttu

**Comment by tbleicher** [comment]
Arttu

I have stopped maintaining this extension. I have no access to a current SketchUp installation that allows extensions. As such I can't say what could have caused this issue.

**Comment by ArttuTuo** [comment]
In config_class.rb, I replaced line 221 (printf "%s\n" % msg.rstrip()) with: printf "%s\n",msg.rstrip()
This change solved the problem.
